# Generated by Django 3.1.2 on 2020-11-27 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=200, null=True)),
                ('judul_artikel', models.CharField(max_length=200, null=True)),
                ('short_line', models.CharField(max_length=200, null=True)),
                ('isi_artikel', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_berita', models.CharField(max_length=200, null=True)),
                ('short_line', models.CharField(max_length=200, null=True)),
                ('isi_berita', models.CharField(max_length=900, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200, null=True)),
                ('jurusan', models.CharField(max_length=200, null=True)),
                ('commentar', models.CharField(max_length=200, null=True)),
                ('berita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreApp.berita')),
            ],
        ),
    ]
