# Generated by Django 3.1.2 on 2020-12-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_contact', models.CharField(choices=[('Guru', 'Guru'), ('Ekstrakulikuler', 'Ekstrakulikuler'), ('Osis', 'Osis')], max_length=200, null=True)),
                ('nama_jenis', models.CharField(max_length=200, null=True)),
                ('nama', models.CharField(max_length=200, null=True)),
                ('nomor_hp', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='berita',
            name='isi_berita',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
