# Generated by Django 3.1.2 on 2020-12-01 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0003_berita_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='tanggal',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
